Taxation Rules Import documentation
Contabilone/emites-server-api-docs pull request #22
Opened 2020-10-28 11:08 UTC by maxsalles

[174679356](https://www.pivotaltracker.com/story/show/174679356)

2020-10-29 13:24 UTC, cacilhas requested changes

2020-10-29 13:24 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +8. Para um CSV com muitas linhas, é conveniente utilizar o serviço de [webhooks](#importa-o-de-regras-tribut-rias-conclu-da) para ser notificado após o fim do processo
Em Markdown, assim como você usa `-` pra gerar uma lista, você usar `1.` pra gerar uma lista enumerada.

Não precisa enumerar manualmente, o MD enumera pra você, basta usar `1.` pra todos os itens.

2020-10-29 13:24 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +  -H 'authorization: Bearer c3b1164e8ae17f6d9712730ec75be6da'
Este _token_ é _fake_, certo?

2020-10-29 13:24 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Temos necessidade de negócio para ser _multipart_? Não poderia ser em um envio _raw_?

2020-10-29 13:25 UTC, maxsalles commented on source/includes/_taxation_rules_import.md
> +  -H 'authorization: Bearer c3b1164e8ae17f6d9712730ec75be6da'
Sim sim, é o mesmo utilizado no resto da documentação.

2020-10-29 13:29 UTC, maxsalles commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Temos sim, o CSV potencialmente pode ser muito grande para ser enviado numa request convencional (que foi minha primeira abordagem inclusive).

2020-10-29 13:58 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Não é pra isso que serve _multipart_.

_Multipart_ é para o envio de **diferentes conteúdos** na mesma requisição, **não** um mesmo conteúdo divido em partes.

2020-10-29 14:24 UTC, ssilvaalexandre commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
A pedido do @cacilhas _O link apresentado foi errado. Esse é de resposta e não requisição. Procurar pelo link de requisição_

2020-10-29 14:24 UTC, brunoliveiralcantara commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
@maxsalles o link que o @cacilhas colou aqui está errado, pode desconsiderar que depois ele vai corrigir e te alertar.

2020-10-29 14:34 UTC, maxsalles commented on source/includes/_taxation_rules_import.md
> +8. Para um CSV com muitas linhas, é conveniente utilizar o serviço de [webhooks](#importa-o-de-regras-tribut-rias-conclu-da) para ser notificado após o fim do processo
Interessante, mas de todo modo acho melhor manter a numeração para facilitar a leitura mesmo quando não é traduzido para o HtML.

2020-10-29 14:53 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Corrigido.

2020-10-29 15:20 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
A AWS tem um protocolo próprio chamado [REST Multipart Upload](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html). Só dá pra usar com AWS, mas a ideia é versátil.

Há um protocolo para _multipart upload_ chamado [TUS](https://tus.io/).

2020-10-30 10:54 UTC, maxsalles commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Interessante essa API da AWS. Contudo, me parece que não teríamos tempo para implementar essa integração até a próxima semana. Teríamos que tratar esses arquivos divididos enviados pelos usuários para, ai sim, na comunicação server -> aws utilizarmos essa API. Também há outro agravante, a complexidade adicional para o usuário, que aparentemente é do tipo que não está esperanto muito esforço para consumir esse _endpoint_.

Sobre o `multipart`, eu iniciei como `raw`, mas buscando informações de qual era a abordagem mais usual me deparei com muitas referências indicando este caminho. Me baseei essencialmente neste post https://www.pluralsight.com/guides/handling-file-upload-using-ruby-on-rails-5-api, e nessas duas APIs https://watershedlrs.zendesk.com/hc/en-us/articles/218210943-Import-a-Data-CSV-via-API e https://panel.dinamize.com/apidoc/#api-5ContactImportGroup-ContactImportAdd.

2020-10-30 12:40 UTC, cacilhas commented on source/includes/_taxation_rules_import.md
> +Observe que, por se tratar do envio de um arquivo, certifique-se que sua requisição será `multipart/form-data`. O arquivo CSV deve ser referenciado através do atributo `file`.
Concordo que não há tempo apra implementar uma abordagem mais sofisticada, no entanto o `multipart/form-data`, em vez de respover o problema, acrescenta um _overhead_ ao dado transportado.

Encontrei também um monte de “artigos” sobre o uso de _multipart_, porém todos eles desconsideram o [_standard_ do protocolo](https://www.ietf.org/rfc/rfc2388.txt) e seu funcionamento!

2020-10-30 19:31 UTC, merged